import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Color Pallette</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <div className="h-36 w-full bg-red-500"></div>
        <div className="h-36 w-full bg-red-700"></div>
        <div className="h-36 w-full bg-rose-600 "></div>
        <div className="h-36 w-full bg-slate-50 flex items-center justify-center p-4">
          <span className="text-lg text-slate-700 ">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum
            doloribus voluptate repellat. Consequuntur aspernatur minima sequi
            sapiente dignissimos praesentium quibusdam, odit nulla quia beatae
            quaerat possimus quo harum hic error.
          </span>
        </div>
        <div className="h-36 w-full bg-slate-500 flex items-center justify-center p-4">
          <span className="text-lg text-slate-50">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum
            doloribus voluptate repellat. Consequuntur aspernatur minima sequi
            sapiente dignissimos praesentium quibusdam, odit nulla quia beatae
            quaerat possimus quo harum hic error.
          </span>
        </div>
        <div className="h-36 w-full bg-slate-900 flex items-center justify-center p-4">
          <span className="text-lg text-slate-50">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum
            doloribus voluptate repellat. Consequuntur aspernatur minima sequi
            sapiente dignissimos praesentium quibusdam, odit nulla quia beatae
            quaerat possimus quo harum hic error.
          </span>
        </div>
      </main>
    </>
  );
};

export default Home;
